spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: postgrespassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # 📩 Kafka Producer Configuration
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        enable.idempotence: true
        retries: 2147483647
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  management:
    endpoints:
      web:
        exposure:
          include: "health,prometheus" # Exposes /actuator/health and /actuator/prometheus